# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bd083d63587733ddeab490276a7402c113e69483f6908715e7c579673235dc24cc5e1dd32111afd688cf23d0a3f1a25076b02bf9ac63020c75fad43b4ecf58

test:
  secret_key_base: 8505ca915e1e626dfaf97870130aa07f526c3e60a3d891846bd82bf41c17f9b49027bfbc49be9fd6cba46e79f70444f9091ba140fa688b120bcfd06aff66bfab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
